name: flutter_invoice_pdf
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pdf: ^3.10.7 # Android, IOS, Linux, MacOS, Windows, Web
  path_provider: ^2.1.1 # Android, IOS, Linux, MacOS, Windows
  open_app_file: ^4.0.2 # Android, IOS, Linux, MacOS, Windows, Web
  intl: ^0.19.0 # Android, IOS, Linux, MacOS, Windows, Web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
